name: Node.js testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          code-version: 16
          cashe: 'npm'
          cashe-dependency-path: '**/package-lock.json'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format
